# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tservicepb\"\x94\x02\n\x17SummarizePodcastRequest\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x12\x14\n\x0c\x61udio_format\x18\x02 \x01(\t\x12\x1a\n\rlanguage_hint\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rgenerate_blog\x18\x04 \x01(\x08\x12\x14\n\x0cgenerate_tts\x18\x05 \x01(\x08\x12\x42\n\x08metadata\x18\x06 \x03(\x0b\x32\x30.servicepb.SummarizePodcastRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x10\n\x0e_language_hint\"\xb6\x02\n\x18SummarizePodcastResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x15\n\rbullet_points\x18\x02 \x03(\t\x12\x19\n\x11summary_paragraph\x18\x03 \x01(\t\x12\x16\n\tblog_post\x18\x04 \x01(\tH\x00\x88\x01\x01\x12 \n\x13summary_audio_bytes\x18\x05 \x01(\x0cH\x01\x88\x01\x01\x12\x43\n\x08metadata\x18\x06 \x03(\x0b\x32\x31.servicepb.SummarizePodcastResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0c\n\n_blog_postB\x16\n\x14_summary_audio_bytes2u\n\x18PodcastSummarizerService\x12Y\n\x0eProcessPodcast\x12\".servicepb.SummarizePodcastRequest\x1a#.servicepb.SummarizePodcastResponseB?Z=github.com/ManoVikram/AI-Podcast-Summarizer/backend/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/ManoVikram/AI-Podcast-Summarizer/backend/api/proto'
  _globals['_SUMMARIZEPODCASTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SUMMARIZEPODCASTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SUMMARIZEPODCASTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_SUMMARIZEPODCASTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SUMMARIZEPODCASTREQUEST']._serialized_start=29
  _globals['_SUMMARIZEPODCASTREQUEST']._serialized_end=305
  _globals['_SUMMARIZEPODCASTREQUEST_METADATAENTRY']._serialized_start=240
  _globals['_SUMMARIZEPODCASTREQUEST_METADATAENTRY']._serialized_end=287
  _globals['_SUMMARIZEPODCASTRESPONSE']._serialized_start=308
  _globals['_SUMMARIZEPODCASTRESPONSE']._serialized_end=618
  _globals['_SUMMARIZEPODCASTRESPONSE_METADATAENTRY']._serialized_start=240
  _globals['_SUMMARIZEPODCASTRESPONSE_METADATAENTRY']._serialized_end=287
  _globals['_PODCASTSUMMARIZERSERVICE']._serialized_start=620
  _globals['_PODCASTSUMMARIZERSERVICE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
