// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummarizePodcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioBytes    []byte                 `protobuf:"bytes,1,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"`
	AudioFormat   string                 `protobuf:"bytes,2,opt,name=audio_format,json=audioFormat,proto3" json:"audio_format,omitempty"`
	LanguageHint  *string                `protobuf:"bytes,3,opt,name=language_hint,json=languageHint,proto3,oneof" json:"language_hint,omitempty"`
	GenerateBlog  bool                   `protobuf:"varint,4,opt,name=generate_blog,json=generateBlog,proto3" json:"generate_blog,omitempty"`
	GenerateTts   bool                   `protobuf:"varint,5,opt,name=generate_tts,json=generateTts,proto3" json:"generate_tts,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizePodcastRequest) Reset() {
	*x = SummarizePodcastRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizePodcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizePodcastRequest) ProtoMessage() {}

func (x *SummarizePodcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizePodcastRequest.ProtoReflect.Descriptor instead.
func (*SummarizePodcastRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *SummarizePodcastRequest) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

func (x *SummarizePodcastRequest) GetAudioFormat() string {
	if x != nil {
		return x.AudioFormat
	}
	return ""
}

func (x *SummarizePodcastRequest) GetLanguageHint() string {
	if x != nil && x.LanguageHint != nil {
		return *x.LanguageHint
	}
	return ""
}

func (x *SummarizePodcastRequest) GetGenerateBlog() bool {
	if x != nil {
		return x.GenerateBlog
	}
	return false
}

func (x *SummarizePodcastRequest) GetGenerateTts() bool {
	if x != nil {
		return x.GenerateTts
	}
	return false
}

func (x *SummarizePodcastRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SummarizePodcastResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Transcript        string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	BulletPoints      []string               `protobuf:"bytes,2,rep,name=bullet_points,json=bulletPoints,proto3" json:"bullet_points,omitempty"`
	SummaryParagraph  string                 `protobuf:"bytes,3,opt,name=summary_paragraph,json=summaryParagraph,proto3" json:"summary_paragraph,omitempty"`
	BlogPost          *string                `protobuf:"bytes,4,opt,name=blog_post,json=blogPost,proto3,oneof" json:"blog_post,omitempty"`
	SummaryAudioBytes []byte                 `protobuf:"bytes,5,opt,name=summary_audio_bytes,json=summaryAudioBytes,proto3,oneof" json:"summary_audio_bytes,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SummarizePodcastResponse) Reset() {
	*x = SummarizePodcastResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizePodcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizePodcastResponse) ProtoMessage() {}

func (x *SummarizePodcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizePodcastResponse.ProtoReflect.Descriptor instead.
func (*SummarizePodcastResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *SummarizePodcastResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SummarizePodcastResponse) GetBulletPoints() []string {
	if x != nil {
		return x.BulletPoints
	}
	return nil
}

func (x *SummarizePodcastResponse) GetSummaryParagraph() string {
	if x != nil {
		return x.SummaryParagraph
	}
	return ""
}

func (x *SummarizePodcastResponse) GetBlogPost() string {
	if x != nil && x.BlogPost != nil {
		return *x.BlogPost
	}
	return ""
}

func (x *SummarizePodcastResponse) GetSummaryAudioBytes() []byte {
	if x != nil {
		return x.SummaryAudioBytes
	}
	return nil
}

func (x *SummarizePodcastResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tservicepb\"\xec\x02\n" +
	"\x17SummarizePodcastRequest\x12\x1f\n" +
	"\vaudio_bytes\x18\x01 \x01(\fR\n" +
	"audioBytes\x12!\n" +
	"\faudio_format\x18\x02 \x01(\tR\vaudioFormat\x12(\n" +
	"\rlanguage_hint\x18\x03 \x01(\tH\x00R\flanguageHint\x88\x01\x01\x12#\n" +
	"\rgenerate_blog\x18\x04 \x01(\bR\fgenerateBlog\x12!\n" +
	"\fgenerate_tts\x18\x05 \x01(\bR\vgenerateTts\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.servicepb.SummarizePodcastRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_language_hint\"\x95\x03\n" +
	"\x18SummarizePodcastResponse\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12#\n" +
	"\rbullet_points\x18\x02 \x03(\tR\fbulletPoints\x12+\n" +
	"\x11summary_paragraph\x18\x03 \x01(\tR\x10summaryParagraph\x12 \n" +
	"\tblog_post\x18\x04 \x01(\tH\x00R\bblogPost\x88\x01\x01\x123\n" +
	"\x13summary_audio_bytes\x18\x05 \x01(\fH\x01R\x11summaryAudioBytes\x88\x01\x01\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.servicepb.SummarizePodcastResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_blog_postB\x16\n" +
	"\x14_summary_audio_bytes2u\n" +
	"\x18PodcastSummarizerService\x12Y\n" +
	"\x0eProcessPodcast\x12\".servicepb.SummarizePodcastRequest\x1a#.servicepb.SummarizePodcastResponseB?Z=github.com/ManoVikram/AI-Podcast-Summarizer/backend/api/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*SummarizePodcastRequest)(nil),  // 0: servicepb.SummarizePodcastRequest
	(*SummarizePodcastResponse)(nil), // 1: servicepb.SummarizePodcastResponse
	nil,                              // 2: servicepb.SummarizePodcastRequest.MetadataEntry
	nil,                              // 3: servicepb.SummarizePodcastResponse.MetadataEntry
}
var file_service_proto_depIdxs = []int32{
	2, // 0: servicepb.SummarizePodcastRequest.metadata:type_name -> servicepb.SummarizePodcastRequest.MetadataEntry
	3, // 1: servicepb.SummarizePodcastResponse.metadata:type_name -> servicepb.SummarizePodcastResponse.MetadataEntry
	0, // 2: servicepb.PodcastSummarizerService.ProcessPodcast:input_type -> servicepb.SummarizePodcastRequest
	1, // 3: servicepb.PodcastSummarizerService.ProcessPodcast:output_type -> servicepb.SummarizePodcastResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
