// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodcastSummarizerService_ProcessPodcast_FullMethodName = "/servicepb.PodcastSummarizerService/ProcessPodcast"
)

// PodcastSummarizerServiceClient is the client API for PodcastSummarizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodcastSummarizerServiceClient interface {
	ProcessPodcast(ctx context.Context, in *SummarizePodcastRequest, opts ...grpc.CallOption) (*SummarizePodcastResponse, error)
}

type podcastSummarizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodcastSummarizerServiceClient(cc grpc.ClientConnInterface) PodcastSummarizerServiceClient {
	return &podcastSummarizerServiceClient{cc}
}

func (c *podcastSummarizerServiceClient) ProcessPodcast(ctx context.Context, in *SummarizePodcastRequest, opts ...grpc.CallOption) (*SummarizePodcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizePodcastResponse)
	err := c.cc.Invoke(ctx, PodcastSummarizerService_ProcessPodcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodcastSummarizerServiceServer is the server API for PodcastSummarizerService service.
// All implementations must embed UnimplementedPodcastSummarizerServiceServer
// for forward compatibility.
type PodcastSummarizerServiceServer interface {
	ProcessPodcast(context.Context, *SummarizePodcastRequest) (*SummarizePodcastResponse, error)
	mustEmbedUnimplementedPodcastSummarizerServiceServer()
}

// UnimplementedPodcastSummarizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodcastSummarizerServiceServer struct{}

func (UnimplementedPodcastSummarizerServiceServer) ProcessPodcast(context.Context, *SummarizePodcastRequest) (*SummarizePodcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPodcast not implemented")
}
func (UnimplementedPodcastSummarizerServiceServer) mustEmbedUnimplementedPodcastSummarizerServiceServer() {
}
func (UnimplementedPodcastSummarizerServiceServer) testEmbeddedByValue() {}

// UnsafePodcastSummarizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodcastSummarizerServiceServer will
// result in compilation errors.
type UnsafePodcastSummarizerServiceServer interface {
	mustEmbedUnimplementedPodcastSummarizerServiceServer()
}

func RegisterPodcastSummarizerServiceServer(s grpc.ServiceRegistrar, srv PodcastSummarizerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPodcastSummarizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodcastSummarizerService_ServiceDesc, srv)
}

func _PodcastSummarizerService_ProcessPodcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizePodcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodcastSummarizerServiceServer).ProcessPodcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodcastSummarizerService_ProcessPodcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodcastSummarizerServiceServer).ProcessPodcast(ctx, req.(*SummarizePodcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodcastSummarizerService_ServiceDesc is the grpc.ServiceDesc for PodcastSummarizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodcastSummarizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.PodcastSummarizerService",
	HandlerType: (*PodcastSummarizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPodcast",
			Handler:    _PodcastSummarizerService_ProcessPodcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
